services:
  etl:
    build: .
    volumes:
      - ./lake:/lake
      - ./dbt:/app/dbt
      - ./sql:/app/sql
      - ./scripts:/app/scripts
      - ./ingest:/app/ingest
      - ./tests/fixtures:/app/tests/fixtures
    environment:
      LAKE_ROOT: /lake
      DS: ${DS:-2026-06-05}
      DBT_TARGET: local
      OPENLINEAGE_CONFIG: /app/quality/openlineage/openlineage.local.yml
      OPENLINEAGE_NAMESPACE: datalake-etl
      PROMETHEUS_PUSHGATEWAY_URL: http://pushgateway:9091
      PYTHONPATH: /app
    entrypoint: ["python", "scripts/run_pipeline.py"]
    command: ["all"]

  etl-shell:
    build: .
    volumes:
      - ./lake:/lake
      - ./dbt:/app/dbt
      - ./sql:/app/sql
      - ./scripts:/app/scripts
      - ./ingest:/app/ingest
      - ./tests/fixtures:/app/tests/fixtures
    environment:
      LAKE_ROOT: /lake
      DS: ${DS:-2026-06-05}
      DBT_PROFILES_DIR: /app/dbt
      DBT_TARGET: local
    entrypoint: ["/bin/bash"]
    stdin_open: true
    tty: true
